# Generated by Django 5.0 on 2024-04-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_name',
            field=models.CharField(default=200, max_length=20),
            preserve_default=False,
        ),
    ]
